apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-poets-society
  namespace: default
spec:
  replicas: 301
  selector:
    matchLabels:
      app: code-poets-society
  template:
    metadata:
      labels:
        app: code-poets-society
    spec:
      containers:
      - name: website
        image: borntoeatt/code-poets-society:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
